# Generated by Django 3.0.4 on 2020-03-20 04:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_num', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_first_name', models.CharField(max_length=100)),
                ('mentor_middle_name', models.CharField(blank=True, max_length=100)),
                ('mentor_last_name', models.CharField(max_length=100)),
                ('mentor_email', models.EmailField(max_length=100)),
                ('mentor_address', models.CharField(max_length=200)),
                ('mentor_city', models.CharField(max_length=50)),
                ('mentor_state', models.CharField(max_length=50)),
                ('mentor_zip', models.CharField(max_length=10)),
                ('mentor_phone', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('school_address', models.CharField(max_length=200)),
                ('school_city', models.CharField(max_length=50)),
                ('school_state', models.CharField(max_length=50)),
                ('school_zip', models.CharField(max_length=10)),
                ('school_email', models.EmailField(max_length=100)),
                ('school_phone', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Group_Mentor_Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='sma.Grade')),
                ('mentor', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='sma.Mentor')),
                ('school', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='sma.School')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=100)),
                ('student_middle_name', models.CharField(blank=True, max_length=100)),
                ('student_last_name', models.CharField(max_length=100)),
                ('student_gender', models.CharField(max_length=100)),
                ('student_dateofbirth', models.DateTimeField(max_length=50)),
                ('student_email', models.EmailField(max_length=100)),
                ('student_address', models.CharField(max_length=200)),
                ('student_city', models.CharField(max_length=50)),
                ('student_state', models.CharField(max_length=50)),
                ('student_zip', models.CharField(max_length=10)),
                ('student_phone', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='sma.Grade')),
                ('school', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='sma.School')),
            ],
        ),
        migrations.CreateModel(
            name='Session_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_location', models.CharField(max_length=50)),
                ('session_start_date', models.DateTimeField(max_length=20)),
                ('session_end_date', models.DateTimeField(max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sma.Student_Group_Mentor_Assignment')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sma.Mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(max_length=100)),
                ('attendance_grade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sma.Grade')),
                ('attendance_mentor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sma.Mentor')),
                ('attendance_session_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sma.Session_Schedule')),
                ('attendance_student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sma.Student')),
            ],
        ),
    ]
