# Generated by Django 3.0.4 on 2020-03-20 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0002_attendance_grade_mentor_school_session_schedule_student_student_group_mentor_assignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attendance',
            new_name='attendance_ID',
        ),
    ]
