# Generated by Django 3.0.4 on 2020-03-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0003_auto_20200320_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='Present', max_length=50),
        ),
    ]
